import { Metadata } from "next";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: "Reddit",
	description: "Generated by create next app",
};
const inter = Inter({ subsets: ["latin"] });
export default function AuthLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<div>{children}</div>
			</body>
		</html>
	);
}
