import type { Metadata } from "next";
import { Inter } from "next/font/google";

import NavBar from "../components/navbar/NavBar";
import { CssBaseline, ThemeProvider } from "@mui/material";
import { theme } from "@/theme/theme";
import "@/theme/Global.css";

import React from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Reddit",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<ThemeProvider theme={theme}>
				<CssBaseline enableColorScheme />
				<body className={inter.className}>
					<NavBar>{children}</NavBar>
				</body>
			</ThemeProvider>
		</html>
	);
}
